services:
  mysql:
    image: mysql:8.0
    container_name: recipes-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: recipes_db
    ports:
      - "3306:3306"
    volumes:
      - recipes-mysql-data:/var/lib/mysql

volumes:
  recipes-mysql-data:
    external: true
